services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      # THE CORRECT, SIMPLE LISTENER CONFIGURATION
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  authservice:
    build: ./authservice
    container_name: authservice
    restart: on-failure
    ports:
      - "9898:9898"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: authservice
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092 # <-- USE THE STANDARD KAFKA PORT

  userservice:
    build: ./userservice
    container_name: userservice
    restart: on-failure
    ports:
      - "9810:9810"
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: userservice
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092 # <-- USE THE STANDARD KAFKA PORT

volumes:
  mysql-data: